name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'ormatting')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install llvm-14
      run: sudo apt install llvm-14
    - name: Install llvm
      run: sudo apt install llvm
    - name: Default
      run: make
    - name: Optimized and Sanitized
      run: make
    - name: Optimized and No OU
      run: make
    - name: Optimized and all flags
      run: make
    - name: Not optimized and Sanitized
      run: make
    - name: Not optimized and No OU
      run: make
    - name: Not optimized and all flags
      run: make